"""
locustfile.py — Load test for SocialPilot API.

Tool chosen: Locust (Python-native, no extra toolchain, easy for team to run)

Usage:
    pip install locust
    cd backend
    locust -f tests/locustfile.py --host=http://127.0.0.1:8000

Then open http://localhost:8089 and set:
  - Number of users: 10
  - Spawn rate: 2/s
  - Run for 60s

Targets:
  - Requests/sec: >= 50 total across all tasks
  - p95 latency: <= 500ms for content list, <= 300ms for login
"""
import random
import string
from locust import HttpUser, task, between


def _random_suffix(n: int = 6) -> str:
    return "".join(random.choices(string.ascii_lowercase + string.digits, k=n))


class SocialPilotUser(HttpUser):
    """Simulates a logged-in user performing the three highest-traffic operations."""

    # Wait 1-3 seconds between tasks (simulates realistic browser usage)
    wait_time = between(1, 3)

    def on_start(self):
        """Register and log in once per virtual user at startup."""
        suffix = _random_suffix()
        self.email = f"loadtest_{suffix}@test.com"
        self.password = "LoadTest1"
        self.access_token = None

        # Register
        reg_res = self.client.post(
            "/api/auth/register",
            json={
                "email": self.email,
                "password": self.password,
                "username": f"lt_{suffix}",
                "full_name": "Load Test User",
            },
            name="/api/auth/register",
        )
        if reg_res.status_code == 200:
            self.access_token = reg_res.json().get("access_token")
        else:
            # Fallback: try login (user may already exist from prior run)
            login_res = self.client.post(
                "/api/auth/login",
                json={"email": self.email, "password": self.password},
                name="/api/auth/login [fallback]",
            )
            if login_res.status_code == 200:
                self.access_token = login_res.json().get("access_token")

    def _auth_headers(self) -> dict:
        return {"Authorization": f"Bearer {self.access_token}"} if self.access_token else {}

    @task(1)
    def login(self):
        """Task 1: POST /api/auth/login — highest traffic (weight 1)."""
        self.client.post(
            "/api/auth/login",
            json={"email": self.email, "password": self.password},
            name="POST /api/auth/login",
        )

    @task(3)
    def list_content(self):
        """Task 2: GET /content — most-read endpoint (weight 3)."""
        self.client.get(
            "/content",
            headers=self._auth_headers(),
            name="GET /content",
        )

    @task(2)
    def create_and_schedule(self):
        """Task 3: POST /content then POST /scheduled-posts (weight 2)."""
        if not self.access_token:
            return

        # Create content
        content_res = self.client.post(
            "/content",
            json={
                "title": f"Load Test Post {_random_suffix()}",
                "body": "Generated by Locust load test",
                "content_type": "text",
                "status": "draft",
            },
            headers=self._auth_headers(),
            name="POST /content",
        )
        if content_res.status_code != 201:
            return

        content_id = content_res.json().get("id")
        if not content_id:
            return

        # Get social accounts
        sa_res = self.client.get(
            "/social-accounts",
            headers=self._auth_headers(),
            name="GET /social-accounts",
        )
        accounts = sa_res.json() if sa_res.status_code == 200 else []
        if not accounts:
            return

        sa_id = accounts[0]["id"]
        from datetime import datetime, timedelta, timezone
        future_time = (datetime.now(timezone.utc) + timedelta(days=random.randint(1, 30))).isoformat()

        self.client.post(
            "/scheduled-posts",
            json={
                "content_id": content_id,
                "social_account_ids": [sa_id],
                "scheduled_time": future_time,
                "is_recurring": False,
            },
            headers=self._auth_headers(),
            name="POST /scheduled-posts",
        )
