"""create_role_reference_table

Revision ID: 86a9f30ecf8d
Revises: ec17ec4e994d
Create Date: 2026-07-31 16:27:02.044298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a9f30ecf8d'
down_revision = 'ec17ec4e994d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_reference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_responsibilities', sa.JSON(), nullable=False),
    sa.Column('maps_to_auth_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_reference_role_label'), 'role_reference', ['role_label'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_reference_role_label'), table_name='role_reference')
    op.drop_table('role_reference')
    # ### end Alembic commands ###
