"""create_scheduled_posts_and_publishing_logs

Revision ID: c77ca9fc0d75
Revises: ec17ec4e994d
Create Date: 2026-08-01 05:11:50.338547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77ca9fc0d75'
down_revision = 'ec17ec4e994d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'published', 'failed', 'cancelled', name='scheduled_post_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_content_id'), 'scheduled_posts', ['content_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_social_account_id'), 'scheduled_posts', ['social_account_id'], unique=False)
    op.create_table('publishing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduled_post_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='publishing_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_post_id'], ['scheduled_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_logs_scheduled_post_id'), 'publishing_logs', ['scheduled_post_id'], unique=False)
    op.create_index(op.f('ix_publishing_logs_social_account_id'), 'publishing_logs', ['social_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_logs_social_account_id'), table_name='publishing_logs')
    op.drop_index(op.f('ix_publishing_logs_scheduled_post_id'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    op.drop_index(op.f('ix_scheduled_posts_social_account_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_content_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    # ### end Alembic commands ###
